config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :applications, except: [:show]
  end
  resources :applications, only: [:new, :create]
  get '/applications/confirm/:token' => 'applications#confirm_email', as: 'invite_email_confirmation'
end

app/models/spree/application.rb
module Spree
  class Application < Spree::Base
    self.table_name = "spree_invite_applications"
    serialize :form, Invite::ApplicationForm

    before_create { self.confirmation_token = SecureRandom.urlsafe_base64 }
  end
end

app/controllers/spree/admin/applications_controller.rb
module Spree
  module Admin
    class ApplicationsController < Spree::Admin::BaseController
      include RansackDateSearch
      ransack_date_searchable date_col: 'updated_at'

      def index
        @search = Spree::Application.search(params[:q])
        @applications = @search.result
          .page(params[:page])
          .per(params[:per_page] || 20)
        respond_with(@applications)
      end
    end
  end
end

app/controllers/spree/applications_controller.rb
module Spree
  class ApplicationsController < ApplicationController
    def new
      @application = Invite::ApplicationForm.new
    end

    def create
      @application = Invite::ApplicationForm.new(application_params)
      if @application.valid?
        app = create_application
        Invite.configuration.mailer.confirm_email(app.id)
        flash[:notice] = Spree.t('invite.application_received')
        redirect_to '' 
      else
        render :new
      end
    end

    def confirm_email
      application = Spree::Application.find_by_confirmation_token(params[:token]) || not_found
      application.update_attribute 'confirmed', true
      flash[:notice] = Spree.t('invite.application_confirmed')
      redirect_to '' 
    end

    private

    def application_params
      params.require(:invite_application_form).except!(:id).permit!
    end

    def create_application
      Application.create form: @application.to_hash
    end

    def not_found
      raise ActiveRecord::RecordNotFound.new('Not Found')
    end
  end
end

app/helpers/spree/applications_helper.rb
module Spree
  module ApplicationsHelper
  end
end

app/helpers/spree_invite/application_helper.rb
module Spree
  module Invite
    module ApplicationHelper
    end
  end
end

app/views/layouts/spree_invite/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SpreeInvite</title>
  <%= stylesheet_link_tag    "spree_invite/application", media: "all" %>
  <%= javascript_include_tag "spree_invite/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/spree/admin/applications/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:application) %>
<% end %>

<% content_for :table_filter_title do %>
  <%= Spree.t(:application_date_search) %>
<% end %>

<% content_for :table_filter do %>
  <%= search_form_for @search, :url => spree.admin_applications_url  do |s| %>
    <div class="date-range-filter field align-center">
      <%= label_tag nil, Spree.t(:start), :class => 'inline' %>
      <%= s.text_field :updated_at_gt, :class => 'datepicker datepicker-from', :value => datepicker_field_value(params[:q][:updated_at_gt]) %>
      
      <span class="range-divider">
        <i class="icon-arrow-right"></i>
      </span>

      <%= s.text_field :updated_at_lt, :class => 'datepicker datepicker-to', :value => datepicker_field_value(params[:q][:updated_at_lt]) %>
      <%= label_tag nil, Spree.t(:end), :class => 'inline' %>
    </div>

    <div class="date-range-filter field align-center">
      <%#= label_tag nil, Spree.t(:email), :class => 'inline' %>
      <%#= s.text_field :email_eq, style: "width:240px" %>
    </div>

    <div class="actions filter-actions">
      <%= button Spree.t(:search), 'icon-search'  %>
    </div>
  <% end %>
<% end %>

<% if @applications.any? %>
  <table class="index" id='listing_applications'>
    <colgroup>
      <col style="width: 30%">
      <col style="width: 20%">
      <col style="width: 15%">
      <col style="width: 15%">
      <col style="width: 20%">
    </colgroup>
    <thead>
      <tr data-hook="admin_applications_index_headers">
        <th><%= Spree.t(:email) %></th>
        <th><%= Spree.t(:plan) %></th>
        <th data-hook="admin_recurring_plans_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @applications.each do |application|%>
        <tr data-hook="admin_applications_index_rows" class="<%= cycle('odd', 'even')%>">
          <td class="align-center"><%= application.email %></td>
          <td data-hook="admin_recurring_plans_index_row_actions" class="actions">
            TODO
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <%= paginate @applications %>
<% else %>
  <div class="alpha sixteen columns no-objects-found">
    <%= Spree.t(:no_resource_found, resource: I18n.t(:other, scope: 'activerecord.models.spree/application')) %>
  </div>
<% end %>

app/views/spree/admin/shared/sub_menu/_invites.html.erb
<ul id="sidebar-invites" class="collapse nav nav-pills nav-stacked" data-hook="admin_invites_sub_tabs">
  <%= tab :applications %>
</ul>

app/views/spree/applications/new.html.erb
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @application } %>

<%= form_for @application, url: applications_path do |f| %>
  <div>
    <p class="field" data-hook="first_name">
      <%= label_tag "first_name", Spree.t(:expiration) %><span class="required">*</span><br />
      <%= text_field_tag "first_name", '', :id => 'first_name', :class => "required", :placeholder => "First name" %>
    </p>
  </div>
  
  <%= f.submit Spree.t(:apply), class: 'continue' %>
  <script>Spree.disableSaveOnClick();</script>
<% end %>